DROP DATABASE IF EXISTS craigslist;

CREATE DATABASE craigslist;

\c craigslist

CREATE TABLE region
(
  id SERIAL PRIMARY KEY,
  region TEXT NOT NULL
);

CREATE TABLE users
(
  id SERIAL PRIMARY KEY,
  user_name VARCHAR(20) NOT NULL,
  preferred_region INT NOT NULL REFERENCES region ON DELETE SET NULL
);

CREATE TABLE category
(
  id SERIAL PRIMARY KEY,
  category INT NOT NULL
);

CREATE TABLE posts
(
  id SERIAL PRIMARY KEY,
  title VARCHAR(40) NOT NULL,
  post_text TEXT NOT NULL,
  user_name INT NOT NULL REFERENCES users ON DELETE CASCADE,
  category INT NOT NULL REFERENCES category ON DELETE SET NULL
);